### ISSUE TITLE
Tmux statusbar

### ISSUE THREAD

**Issue by CaioBianchi** [KeitaNakamura/neodark.vim#10]
Hi there,

I was wondering if you could share your tmux statusline (from the screenshot). Looks pretty sick! :)

**Comment by KeitaNakamura** [comment]
Hi. Okey, I made a repository to set up tmux statusbar ([tmux-statusbar](https://github.com/KeitaNakamura/tmux-statusbar)). Please check it out!

**Comment by CaioBianchi** [comment]
Sweet! Thanks @KeitaNakamura
