### ISSUE TITLE
How to get colors from the screenshot?

### ISSUE THREAD

**Issue by rdev** [KeitaNakamura/neodark.vim#11]
Sorry if the question is dumb, I'm very new to Vim, but here's the screenshot from the readme:
<img width="379" alt="screen shot 2017-09-30 at 7 36 50 pm" src="https://raw.githubusercontent.com/KeitaNakamura/neodark.vim/master/default.png">
And here's what I get after installing neodark:
 
<img width="379" alt="screen shot 2017-09-30 at 7 36 50 pm" src="https://user-images.githubusercontent.com/8418866/31045452-f6af65bc-a616-11e7-9265-1904d91316da.png">

What am I doing wrong?

**Comment by rdev** [comment]
Turns out Tmux screws up true color, nevermind

**Comment by Xosmond** [comment]
@fivepointseven How did u solve it? I have the same problem.
