### ISSUE TITLE
The terminal_transparent option doesn't seem to work for me.

### ISSUE THREAD

**Issue by cm-s** [KeitaNakamura/neodark.vim#12]
This is the contents of my `.vimrc`.
```
filetype plugin indent on
call plug#begin('~/.vim/vim-plugins')
Plug 'KeitaNakamura/neodark.vim'
Plug 'https://github.com/joshdick/onedark.vim'
call plug#end()

colorscheme neodark
let g:neodark#terminal_transparent = 1
let g:neodark#use_256color = 1
```
![screenshot_20171027_220854](https://user-images.githubusercontent.com/16346485/32131483-d7144274-bb63-11e7-9fcf-b79e40620aff.png)
> **And this is my background when editing.**

![screenshot_20171027_221250](https://user-images.githubusercontent.com/16346485/32131489-0c3d5774-bb64-11e7-8916-86d045f35719.png)

**Comment by KeitaNakamura** [comment]
Hi.
Could you try to put those settings before `colorscheme neodark`?

```vim
let g:neodark#terminal_transparent = 1
let g:neodark#use_256color = 1
colorscheme neodark
```

**Comment by cm-s** [comment]
Very nice, it worked. :)
Thanks, and great looking colorscheme!
