### ISSUE TITLE
Feature Request: Xresources colours

### ISSUE THREAD

**Issue by timtro** [KeitaNakamura/neodark.vim#14]
Thanks for the beautiful colorscheme.

Noticeably absent is an Xresources colour definition :)

If I can scrape together some time, (and you're open to it) I'll contribute this myself. But on the off chance you (or someone else reading this) has one already, I thought I would be a good idea to formally create the issue.

**Comment by KeitaNakamura** [comment]
Hi.
Unfortunately, I don't have Xresources color definition but I'm happy to support it :)
