### ISSUE TITLE
Change color of Tex Coneal

### ISSUE THREAD

**Issue by isakhammer** [KeitaNakamura/neodark.vim#32]
Hi, I am writing a project report in latex using vim and the neodark colorscheme.
However, the tex conceal is quite dim and I have to concentrate hard to read sometimes. Do you have any idea on how to change the color of the conceal?
![image](https://user-images.githubusercontent.com/43385748/172169423-f0dda3f7-bee7-4027-9d2e-e2514af58c59.png)

**Comment by KeitaNakamura** [comment]
Hi. In neodark.vim, gray is not used for Conceal (see [this line](https://github.com/KeitaNakamura/neodark.vim/blob/bd422a98e7293013d67ccfbe1d52e1144ab47083/colors/neodark.vim#L320)). So I think the gray color is come from other plugins, e.g., [Yggdroot/indentLine](https://github.com/KeitaNakamura/neodark.vim/blob/bd422a98e7293013d67ccfbe1d52e1144ab47083/colors/neodark.vim#L320).

**Comment by isakhammer** [comment]
Thanks a lot! I removed IndentLine plugin and everything worked fine.
![image](https://user-images.githubusercontent.com/43385748/173023210-d7a0bc28-bbb2-4439-957f-21ee04fc3bba.png)
