### ISSUE TITLE
Lightline and airline issue

### ISSUE THREAD

**Issue by atharvaaalok** [KeitaNakamura/neodark.vim#34]
Hello,
First of all, thank you very much for creating this plug-in.
I am facing an issue with lightline. (I have posted it on vim StackExchange [here ](https://vi.stackexchange.com/questions/41724/lightline-and-airline-with-neodark-vim) as well)
My .vimrc looks like:
![Capture](https://user-images.githubusercontent.com/62356986/229088798-0fc25f5e-7da9-43a6-b345-e6d4149effad.PNG)

But the lightline feature is not active.
![Capture1](https://user-images.githubusercontent.com/62356986/229088943-924e1ea7-3664-4f69-bf9d-276393a211bb.PNG)

How can I fix this issue?
Also the font that I have is different from the one in the image in the README.md
How can I change that too?

ありがとう　ございます

**Comment by atharvaaalok** [comment]
I got this working! I got an answer on vim StackExchange.

Thought I am still confused about how to setup .vimrc for airline.
You have the following line in README.md "For airline, just use!"

I am finding this confusing ;)

**Comment by KeitaNakamura** [comment]
Hi, sorry for late reply and confusing you.
You need to install lightline as well.
“Just use” means that there is no need to write configuration in vimrc.
Enjoy vim life :)

**Comment by KeitaNakamura** [comment]
Oh, sorry I’m misunderstanding. You still have a problem with lightline configuration. See [this](https://github.com/KeitaNakamura/dotfiles/blob/82071b70e83432f7180520e5793bdb5019c1757a/.vimrc#L270) , and change the color scheme entry “aurora” to “neodark”.
