### ISSUE TITLE
Update Airline Theme

### ISSUE THREAD

**Issue by TheBabu** [KeitaNakamura/neodark.vim#8]
Hello there!
I was wondering if you could update your Airline theme, because I cannot figure out anything that going is on in your Airline theme even after reading the wiki a whole bunch of times...

![screenshot_2017-05-02_20-40-23](https://cloud.githubusercontent.com/assets/24832107/25647592/1308884e-2f78-11e7-95bc-3d15f5051d41.png)

Thanks!
P.S.I really like your neodark themes!

**Comment by KeitaNakamura** [comment]
Hi!

I'm using `lightline` (not `airline`) actually. For airline, you would get following theme without any setting (you can see minimal vimrc in picture).

<img width="802" alt="screen shot 2017-05-04 at 3 14 23" src="https://cloud.githubusercontent.com/assets/16015926/25675095/36807fe2-3078-11e7-8281-c69ad43ecc54.png">

If you prefer the theme in README rather than above theme, try this:

<img width="802" alt="screen shot 2017-05-04 at 3 20 34" src="https://cloud.githubusercontent.com/assets/16015926/25675247/b9252c5e-3078-11e7-8bfb-12d46bc41716.png">

**Comment by TheBabu** [comment]
Hmmm I think the problem that I have is that I have not installed your theme using your plugin, I'll try install it! Thank you for the reply!
EDIT:
Ah I think I know why your theme does not look my theme! After rereading the actual vim colors that you have, it has it so that when the background is transparent it changes the colors! I'll do a little hack to that!

Second Edit:
After some tinkering around, I am wondering how to make the z section color in airline on to the very bright a little bit brighter? If you could help me out with, that would be much appreciated!

Third Edit:
After tinkering A LOT with my that file, I have a deeper understanding on vim scripting... and know how to correctly change the colors know... So I have changed the colors to something I wanted! Closing this thread!

**Comment by KeitaNakamura** [comment]
Oh, sorry, I haven't noticed your message. I couldn't get any notification when you just edit your comment.

**Comment by TheBabu** [comment]
Ahaha I actually think it was better that you didn't reply because now, I know how to program vim scripts! :P

**Comment by KeitaNakamura** [comment]
I checked the theme when the background is transparent, and realized that all colors are brighter than default. Could you fix this problem?

**Comment by TheBabu** [comment]
I thought you made it when you are have a transparent background the colors change?
```vim
" Transparent Background
if g:neodark#terminal_transparent == 1
  let s:base1[1] = 'none' " This doesn't work well for airline
end
```
Or am I interpreting this code wrong?

**Comment by KeitaNakamura** [comment]
It's not ideal that the colors (blue, red, green, etc.) become brighter in the transparent background case. In my code, `base1` is mostly used for background color, so I changed it to `none` for transparent case. But as you said,

> After rereading the actual vim colors that you have, it has it so that when the background is transparent it changes the colors!

other colors also change. I have no idea to make background transparent in a correct way.

**Comment by TheBabu** [comment]
Hmmm.... maybe try doing `set termguicolors`, I have seen multiple vim scripts use this, and I think that is the reason why.

**Comment by KeitaNakamura** [comment]
It couldn't be help. I thought that you also had same problem. Thanks, anyway!

**Comment by TheBabu** [comment]
Haha... No need, I didn't really help you in the first place... :P
